"use client";

import { useEffect,useState } from "react";
import { Flame, ShieldCheck, WalletCards, CheckCircle2, Loader2, ChevronDown } from "lucide-react";
import { createPublicClient, createWalletClient, custom, http, parseUnits } from "viem";
import { arbitrum, base, mainnet, optimism, polygon } from "viem/chains";
import { supabase } from "../../../lib/supabase/client";

declare global { interface Window { ethereum?: { request:(args:{method:string;params?:unknown[]})=>Promise<unknown> } } }

const erc20Abi=[{type:"function",name:"allowance",stateMutability:"view",inputs:[{name:"owner",type:"address"},{name:"spender",type:"address"}],outputs:[{type:"uint256"}]},{type:"function",name:"approve",stateMutability:"nonpayable",inputs:[{name:"spender",type:"address"},{name:"amount",type:"uint256"}],outputs:[{type:"bool"}]}] as const;
const gmAbi=[{type:"function",name:"gm",stateMutability:"nonpayable",inputs:[],outputs:[]} ] as const;
const networks:{key:string;label:string;chain:any}[]=[{key:"base",label:"Base Mainnet",chain:base},{key:"ethereum",label:"Ethereum Mainnet",chain:mainnet},{key:"arbitrum",label:"Arbitrum One",chain:arbitrum},{key:"optimism",label:"OP Mainnet",chain:optimism},{key:"polygon",label:"Polygon",chain:polygon}];

type Network={id:string;network_key:string;display_name:string;chain_id:number;contract_address:string;explorer_tx_base_url:string;fee_token_symbol:string;fee_token_address:string};

export default function GM(){
 const [wallet,setWallet]=useState("");const [streak,setStreak]=useState(0);const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);const [txHash,setTxHash]=useState("");const [completed,setCompleted]=useState(false);const [recoveryHash,setRecoveryHash]=useState("");const [recoveryBusy,setRecoveryBusy]=useState(false);const [networks,setNetworks]=useState<Network[]>([]);const [selected,setSelected]=useState<Network|null>(null);

 useEffect(()=>{let active=true;(async()=>{const [{data:n},{data:s}]=await Promise.all([supabase.from("bozi_gm_networks").select("id,network_key,display_name,chain_id,contract_address,explorer_tx_base_url,fee_token_symbol,fee_token_address").eq("enabled",true).order("display_name"),supabase.auth.getSession()]);if(!active)return;setNetworks((n??[]) as Network[]);if(n?.length)setSelected((n as Network[]).find(x=>x.network_key==="base")??(n[0] as Network));if(!s.session)return;const {data:rows}=await supabase.from("bozi_gm_checkins").select("checkin_date").eq("user_id",s.session.user.id).eq("status","confirmed").order("checkin_date",{ascending:false}).limit(90);if(!rows?.length){if(active)setStreak(0);return;}const dates=new Set(rows.map(x=>x.checkin_date));const cursor=new Date(`${rows[0].checkin_date}T00:00:00Z`);let count=0;while(dates.has(cursor.toISOString().slice(0,10))){count++;cursor.setUTCDate(cursor.getUTCDate()-1)}if(active)setStreak(count)})();return()=>{active=false}},[completed]);

 const chainMeta=(key:string)=>networks.find(n=>n.network_key===key)?.chain_id===8453?base:networks.find(n=>n.network_key===key)?.chain_id===1?mainnet:networks.find(n=>n.network_key===key)?.chain_id===42161?arbitrum:networks.find(n=>n.network_key===key)?.chain_id===10?optimism:networks.find(n=>n.network_key===key)?.chain_id===137?polygon:null;

 async function connectWallet(){if(!window.ethereum){setStatus("Install an EVM wallet such as MetaMask or Coinbase Wallet.");return}try{const a=(await window.ethereum.request({method:"eth_requestAccounts"})) as string[];if(a?.[0])setWallet(a[0].toLowerCase())}catch(e){setStatus(e instanceof Error?e.message:"Wallet connection cancelled.")}}
 async function switchChain(chainId:number){if(!window.ethereum)throw new Error("Wallet not found.");try{await window.ethereum.request({method:"wallet_switchEthereumChain",params:[{chainId:"0x"+chainId.toString(16)}]})}catch(e:any){if(e?.code!==4902)throw e;throw new Error("Add this network to your wallet before continuing.")}}

 async function verify(hash:string){const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("Your Bozi session expired. Please sign in again.");const response=await fetch("/api/gm/verify",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({txHash:hash,walletAddress:wallet,networkKey:selected?.network_key})});const result=await response.json();if(!response.ok)throw new Error(result.error||"GM verification failed.");setCompleted(true);setTxHash(hash);setStatus(result.pointsAwarded>0?"+50 points earned.": "GM already recorded.")}

 async function submitGM(){if(!selected){setStatus("No GM network is enabled yet.");return}if(!window.ethereum){await connectWallet();return}if(!wallet){await connectWallet();return}setBusy(true);setCompleted(false);setTxHash("");setStatus("Preparing "+selected.display_name+" transaction…");try{const chain=chainMeta(selected.network_key);if(!chain)throw new Error("This network is not supported in the wallet interface yet.");await switchChain(selected.chain_id);const walletClient=createWalletClient({chain,transport:custom(window.ethereum)});const publicClient=createPublicClient({chain,transport:http(chain.rpcUrls.default.http[0])});const account=wallet as `0x${string}`;const fee=parseUnits("0.01",6);const allowance=await publicClient.readContract({address:selected.fee_token_address as `0x${string}`,abi:erc20Abi,functionName:"allowance",args:[account,selected.contract_address as `0x${string}`]});if(allowance<fee){setStatus("Approve 0.01 "+selected.fee_token_symbol+"…");const h=await walletClient.writeContract({account,address:selected.fee_token_address as `0x${string}`,abi:erc20Abi,functionName:"approve",args:[selected.contract_address as `0x${string}`,fee],chain});await publicClient.waitForTransactionReceipt({hash:h})}setStatus("Confirm the GM transaction in your wallet…");const hash=await walletClient.writeContract({account,address:selected.contract_address as `0x${string}`,abi:gmAbi,functionName:"gm",chain});setTxHash(hash);setStatus("Waiting for onchain confirmation…");await publicClient.waitForTransactionReceipt({hash});setStatus("Verifying the confirmed GM…");await verify(hash)}catch(e){const message=e instanceof Error?e.message:"";const rejected=/user rejected|user denied|request rejected|rejected the request/i.test(message);setStatus(rejected?"Rejected":message||"GM failed. No points were awarded.")}finally{setBusy(false)}}

 async function verifyExisting(){if(!/^0x[a-fA-F0-9]{64}$/.test(recoveryHash.trim())){setStatus("Enter a valid transaction hash.");return}if(!wallet||!selected){setStatus("Connect your wallet and select the network.");return}setRecoveryBusy(true);setStatus("Verifying the existing GM…");try{await verify(recoveryHash.trim()) ;setRecoveryHash("")}catch(e){const message=e instanceof Error?e.message:"";setStatus(/user rejected|user denied|request rejected|rejected the request/i.test(message)?"Rejected":message||"Unable to verify the GM.")}finally{setRecoveryBusy(false)}}

 return <div className="mx-auto max-w-4xl px-4 py-8 pb-24 md:px-8 md:py-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--lime)]">Daily onchain activity</p><h1 className="mt-2 text-3xl font-black">GM Streak</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">Choose an enabled network, sign the GM transaction, and earn points only after the transaction is confirmed and verified onchain.</p>
  <div className="mt-8 grid gap-4 md:grid-cols-[1.25fr_.75fr]"><section className="rounded-3xl border border-[var(--line)] bg-[var(--panel)] p-6 md:p-8"><div className="flex items-center gap-4"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[var(--lime)]/10 text-[var(--lime)]"><Flame/></div><div><p className="text-sm text-[var(--muted)]">Current streak</p><p className="text-3xl font-black">{streak} {streak===1?"day":"days"}</p></div></div>
   <div className="mt-8 rounded-2xl border border-[var(--line)] bg-white/[.025] p-5"><label className="text-xs font-semibold text-[var(--muted)]">GM network</label><div className="relative mt-2"><select value={selected?.network_key??""} onChange={e=>{const n=networks.find(x=>x.network_key===e.target.value);if(n)setSelected(n)}} className="w-full appearance-none rounded-xl border border-[var(--line)] bg-[#11151b] px-3 py-3 pr-9 text-sm"><option value="" disabled>Select network</option>{networks.map(n=><option key={n.id} value={n.network_key}>{n.display_name} · {n.fee_token_symbol}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-3.5" size={16}/></div><p className="mt-2 text-xs text-[var(--muted)]">0.01 {selected?.fee_token_symbol??"token"} fee + normal network gas.</p><button onClick={submitGM} disabled={busy||!selected} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--lime)] px-4 py-3 text-sm font-bold text-black disabled:opacity-60">{busy?<Loader2 size={17} className="animate-spin"/>:completed?<CheckCircle2 size={17}/>:<WalletCards size={17}/>} {busy?"Processing…":wallet?"GM on "+(selected?.display_name??"network"):"Connect wallet to GM"}</button>{status&&<p className="mt-3 text-center text-xs font-semibold text-[var(--lime)]">{status}</p>}{txHash&&selected&&<a href={selected.explorer_tx_base_url+txHash} target="_blank" rel="noreferrer" className="mt-2 block text-center text-xs underline">View transaction</a>}{wallet&&selected&&<div className="mt-5 border-t border-[var(--line)] pt-4"><p className="text-[11px] font-semibold text-[var(--muted)]">Already completed a GM?</p><input value={recoveryHash} onChange={e=>setRecoveryHash(e.target.value)} placeholder="Paste transaction hash" className="mt-3 w-full rounded-xl border border-[var(--line)] bg-black/10 px-3 py-2 text-xs outline-none"/><button onClick={verifyExisting} disabled={recoveryBusy||!recoveryHash.trim()} className="mt-2 w-full rounded-xl border border-[var(--line)] px-3 py-2 text-xs font-bold disabled:opacity-50">{recoveryBusy?"Verifying…":"Verify existing GM"}</button></div>}</div>
  </section><section className="rounded-3xl border border-[var(--line)] bg-[var(--panel)] p-6"><p className="text-sm font-bold">How it works</p><div className="mt-5 space-y-3 text-sm"><Info icon={WalletCards} title="Onchain confirmation" text="A successful GM transaction is required before points are awarded."/><Info icon={ShieldCheck} title="50 points" text="Each confirmed GM earns 50 points."/><Info icon={Flame} title="0.01 fee" text="The configured fee token is charged by the deployed GM contract." /></div></section></div>
  {networks.length===0&&<div className="mt-5 rounded-xl border border-dashed border-[var(--line)] p-4 text-sm text-[var(--muted)]">No GM network is enabled yet.</div>}
 </div>;
}
function Info({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="flex gap-3 rounded-xl border border-[var(--line)] p-3"><Icon size={17} className="mt-0.5 text-[var(--lime)]"/><div><p className="font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{text}</p></div></div>}
