"use client";

import { useEffect,useState } from "react";
import { FilePlus2, Loader2, Plus, Save, ShieldCheck, Users } from "lucide-react";
import { supabase } from "../../../lib/supabase/client";

type Quest={id:string;slug:string;title:string;summary:string|null;lesson_points:number;social_points:number;social_task_enabled:boolean;social_instructions:string|null;status:string};
type Lesson={id:string;quest_id:string;position:number;title:string;content_md:string};
type Question={id:string;lesson_id:string;position:number;prompt:string;options:any;correct_option_key:string;explanation:string|null;points:number};
type Submission={id:string;post_url:string;status:string;points_awarded:number;submitted_at:string;display_name:string|null;x_handle:string|null};

export default function Admin(){
 const [allowed,setAllowed]=useState<boolean|null>(null);const [quests,setQuests]=useState<Quest[]>([]);const [selected,setSelected]=useState<Quest|null>(null);const [lessons,setLessons]=useState<Lesson[]>([]);const [lesson,setLesson]=useState<Lesson|null>(null);const [questions,setQuestions]=useState<Question[]>([]);const [submissions,setSubmissions]=useState<Submission[]>([]);
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");

 useEffect(()=>{(async()=>{const {data}=await supabase.rpc("bozi_is_admin");setAllowed(Boolean(data));if(data){await loadQuests();await loadSubmissions()}})()},[]);
 const loadQuests=async()=>{const {data,error}=await supabase.rpc("bozi_admin_list_quests");if(error)setMessage(error.message);else setQuests((data??[]) as Quest[])};
 const loadSubmissions=async()=>{const {data}=await supabase.rpc("bozi_admin_list_submissions");if(!data)return;setSubmissions(data as Submission[])};
 const selectQuest=async(q:Quest)=>{setSelected(q);setLesson(null);setQuestions([]);const {data}=await supabase.rpc("bozi_admin_list_lessons",{p_quest_id:q.id});setLessons((data??[]) as Lesson[])};
 const selectLesson=async(l:Lesson)=>{setLesson(l);const {data}=await supabase.rpc("bozi_admin_list_questions",{p_lesson_id:l.id});setQuestions((data??[]) as Question[])};
 const saveQuest=async()=>{if(!selected)return;setBusy(true);const {data,error}=await supabase.rpc("bozi_admin_upsert_quest",{p_id:selected.id,p_slug:selected.slug,p_title:selected.title,p_summary:selected.summary??"",p_lesson_points:Number(selected.lesson_points),p_social_points:Number(selected.social_points),p_social_task_enabled:selected.social_task_enabled,p_social_instructions:selected.social_instructions??"",p_status:selected.status});setMessage(error?error.message:"Quest saved.");if(!error)await loadQuests();setBusy(false)};
 const newQuest=()=>{setSelected({id:"",slug:"new-quest",title:"New quest",summary:"",lesson_points:10,social_points:20,social_task_enabled:false,social_instructions:"",status:"draft"});setLessons([]);setLesson(null);setQuestions([])};
 const saveLesson=async()=>{if(!selected||!lesson)return;setBusy(true);const {data,error}=await supabase.rpc("bozi_admin_upsert_lesson",{p_id:lesson.id||null,p_quest_id:selected.id,p_position:Number(lesson.position),p_title:lesson.title,p_content_md:lesson.content_md});setMessage(error?error.message:"Lesson saved.");if(!error){const {data:ls}=await supabase.rpc("bozi_admin_list_lessons",{p_quest_id:selected.id});setLessons((ls??[]) as Lesson[]);if(data)setLesson({...lesson,id:String(data)})}setBusy(false)};
 const newLesson=()=>setLesson({id:"",quest_id:selected?.id||"",position:lessons.length+1,title:"New lesson",content_md:"# Lesson\n\nWrite the lesson here."});
 const saveQuestion=async(q:Question)=>{if(!lesson)return;setBusy(true);const {data,error}=await supabase.rpc("bozi_admin_upsert_question",{p_id:q.id||null,p_lesson_id:lesson.id,p_position:Number(q.position),p_prompt:q.prompt,p_options:q.options,p_correct_option_key:q.correct_option_key,p_explanation:q.explanation??"",p_points:Number(q.points)});setMessage(error?error.message:"Question saved.");if(!error){const {data:qs}=await supabase.rpc("bozi_admin_list_questions",{p_lesson_id:lesson.id});setQuestions((qs??[]) as Question[])}setBusy(false)};
 const review=async(id:string,status:string)=>{setBusy(true);const {error}=await supabase.rpc("bozi_admin_review_submission",{p_submission_id:id,p_status:status,p_note:"Reviewed in Bozi admin"});setMessage(error?error.message:"Submission updated.");if(!error)await loadSubmissions();setBusy(false)};

 if(allowed===null)return <div className="mx-auto max-w-6xl px-4 py-10 text-sm text-[var(--muted)]">Checking admin access…</div>;
 if(!allowed)return <div className="mx-auto max-w-6xl px-4 py-10"><h1 className="text-3xl font-black">Admin</h1><p className="mt-3 text-sm text-[var(--muted)]">This account is not authorized for Bozi administration.</p></div>;

 return <div className="mx-auto max-w-7xl px-4 py-8 pb-24 md:px-8 md:py-10">
  <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--violet)]">Operations</p><h1 className="mt-2 text-3xl font-black">Admin</h1><p className="mt-2 text-sm text-[var(--muted)]">Build published education, manage rewards, and review contributions.</p></div><button onClick={newQuest} className="inline-flex items-center gap-2 rounded-xl bg-[var(--lime)] px-4 py-3 text-sm font-bold text-black"><Plus size={16}/> New quest</button></div>
  {message&&<div className="mt-5 rounded-xl border border-[var(--line)] bg-[var(--panel)] p-3 text-xs text-[var(--muted)]">{message}</div>}
  <div className="mt-8 grid gap-5 xl:grid-cols-[300px_1fr]">
   <section className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-4"><div className="flex items-center justify-between"><h2 className="font-bold">Quests</h2><FilePlus2 size={17}/></div><div className="mt-4 space-y-2">{quests.map(q=><button key={q.id} onClick={()=>selectQuest(q)} className={"w-full rounded-xl border p-3 text-left "+(selected?.id===q.id?"border-[var(--lime)] bg-[var(--lime)]/5":"border-[var(--line)]")}><p className="truncate text-sm font-semibold">{q.title}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{q.status} · {q.slug}</p></button>)}</div></section>
   <section className="space-y-5">
    {selected?<><div className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-5"><div className="grid gap-3 md:grid-cols-2"><Field label="Title"><input value={selected.title} onChange={e=>setSelected({...selected,title:e.target.value})}/></Field><Field label="Slug"><input value={selected.slug} onChange={e=>setSelected({...selected,slug:e.target.value})}/></Field><Field label="Lesson points"><input type="number" value={selected.lesson_points} onChange={e=>setSelected({...selected,lesson_points:Number(e.target.value)})}/></Field><Field label="Social points"><input type="number" value={selected.social_points} onChange={e=>setSelected({...selected,social_points:Number(e.target.value)})}/></Field><Field label="Status"><select value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value})}><option>draft</option><option>published</option><option>archived</option></select></Field><label className="flex items-center gap-2 pt-6 text-sm"><input type="checkbox" checked={selected.social_task_enabled} onChange={e=>setSelected({...selected,social_task_enabled:e.target.checked})}/> X task enabled</label></div><Field label="Summary"><textarea value={selected.summary??""} onChange={e=>setSelected({...selected,summary:e.target.value})}/></Field><Field label="X task instructions"><textarea value={selected.social_instructions??""} onChange={e=>setSelected({...selected,social_instructions:e.target.value})}/></Field><button onClick={saveQuest} disabled={busy} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-[var(--lime)] px-4 py-3 text-sm font-bold text-black"><Save size={15}/>Save quest</button></div>
     <div className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Lessons</h2><button onClick={newLesson} disabled={!selected.id} className="rounded-lg border border-[var(--line)] px-3 py-2 text-xs font-bold">Add lesson</button></div><div className="mt-4 grid gap-3 md:grid-cols-2">{lessons.map(l=><button key={l.id} onClick={()=>selectLesson(l)} className={"rounded-xl border p-3 text-left "+(lesson?.id===l.id?"border-[var(--violet)]":"border-[var(--line)]")}><span className="text-[10px] text-[var(--muted)]">Lesson {l.position}</span><p className="mt-1 text-sm font-semibold">{l.title}</p></button>)}</div>{lesson&&<div className="mt-5 border-t border-[var(--line)] pt-5"><div className="grid gap-3 md:grid-cols-[80px_1fr]"><Field label="Pos"><input type="number" value={lesson.position} onChange={e=>setLesson({...lesson,position:Number(e.target.value)})}/></Field><Field label="Title"><input value={lesson.title} onChange={e=>setLesson({...lesson,title:e.target.value})}/></Field></div><Field label="Markdown lesson"><textarea className="min-h-48" value={lesson.content_md} onChange={e=>setLesson({...lesson,content_md:e.target.value})}/></Field><button onClick={saveLesson} disabled={busy||!selected.id} className="rounded-xl border border-[var(--line)] px-4 py-2.5 text-sm font-bold">Save lesson</button></div>}</div>
     {lesson?.id&&<div className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Questions</h2><button onClick={()=>setQuestions([...questions,{id:"",lesson_id:lesson.id,position:questions.length+1,prompt:"New question",options:[{key:"a",label:"Option A"},{key:"b",label:"Option B"}],correct_option_key:"a",explanation:"",points:10}])} className="rounded-lg border border-[var(--line)] px-3 py-2 text-xs font-bold">Add question</button></div><div className="mt-4 space-y-4">{questions.map((q,i)=><QuestionEditor key={q.id||"new-"+i} q={q} onChange={next=>setQuestions(questions.map((x,j)=>j===i?next:x))} onSave={()=>saveQuestion(q)} busy={busy}/>)}</div></div>}</>:<div className="rounded-2xl border border-dashed border-[var(--line)] p-10 text-sm text-[var(--muted)]">Select a quest or create a new one.</div>}
   </section>
  </div>
  <section className="mt-8 rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-5"><div className="flex items-center gap-2"><Users size={17}/><h2 className="font-bold">X submissions</h2></div><div className="mt-4 space-y-2">{submissions.length?submissions.map(s=><div key={s.id} className="grid gap-3 rounded-xl border border-[var(--line)] p-3 md:grid-cols-[1fr_auto]"><div><p className="text-sm font-semibold">{s.display_name||s.x_handle||"Participant"} <span className="text-[var(--muted)]">· {s.status}</span></p><a className="text-xs underline" href={s.post_url} target="_blank" rel="noreferrer">{s.post_url}</a><p className="mt-1 text-[10px] text-[var(--muted)]">+{s.points_awarded} points · {new Date(s.submitted_at).toLocaleString()}</p></div><div className="flex items-center gap-2">{s.status==="pending"&&<><button onClick={()=>review(s.id,"approved")} className="rounded-lg bg-[var(--lime)] px-3 py-2 text-xs font-bold text-black">Approve</button><button onClick={()=>review(s.id,"rejected")} className="rounded-lg border border-[var(--line)] px-3 py-2 text-xs font-bold">Reject</button></>}</div></div>):<p className="text-sm text-[var(--muted)]">No social submissions yet.</p>}</div></section>
  <div className="mt-5 flex items-center gap-2 text-xs text-[var(--muted)]"><ShieldCheck size={15} className="text-[var(--lime)]"/> Admin mutations run through server-side security-definer functions.</div>
 </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs font-semibold text-[var(--muted)]">{label}<div className="mt-2">{children}</div></label>}
function InputBase(p:any){return <input {...p} className="w-full rounded-xl border border-[var(--line)] bg-black/10 px-3 py-2.5 text-sm outline-none"/>}
function TextBase(p:any){return <textarea {...p} className="w-full rounded-xl border border-[var(--line)] bg-black/10 px-3 py-2.5 text-sm outline-none"/>}
function SelectBase(p:any){return <select {...p} className="w-full rounded-xl border border-[var(--line)] bg-black/10 px-3 py-2.5 text-sm outline-none"/>}
function QuestionEditor({q,onChange,onSave,busy}:{q:Question;onChange:(q:Question)=>void;onSave:()=>void;busy:boolean}){const options=Array.isArray(q.options)?q.options:[];return <div className="rounded-xl border border-[var(--line)] p-4"><div className="grid gap-3 md:grid-cols-[70px_1fr_90px]"><Field label="Pos"><InputBase type="number" value={q.position} onChange={(e:any)=>onChange({...q,position:Number(e.target.value)})}/></Field><Field label="Prompt"><InputBase value={q.prompt} onChange={(e:any)=>onChange({...q,prompt:e.target.value})}/></Field><Field label="Points"><InputBase type="number" value={q.points} onChange={(e:any)=>onChange({...q,points:Number(e.target.value)})}/></Field></div><div className="mt-3 grid gap-2 md:grid-cols-2">{options.map((o:any,i:number)=><div key={i} className="flex gap-2"><InputBase value={o.label??o.text??String(o)} onChange={(e:any)=>{const next=options.slice();next[i]={...next[i],key:next[i]?.key||String.fromCharCode(97+i),label:e.target.value};onChange({...q,options:next})}}/><button onClick={()=>onChange({...q,correct_option_key:options[i]?.key||String.fromCharCode(97+i)})} className={"rounded-lg px-3 text-xs font-bold "+(q.correct_option_key===(options[i]?.key||String.fromCharCode(97+i))?"bg-[var(--lime)] text-black":"border border-[var(--line)]")}>Correct</button></div>)}</div><div className="mt-3"><Field label="Explanation"><TextBase value={q.explanation??""} onChange={(e:any)=>onChange({...q,explanation:e.target.value})}/></Field></div><button onClick={onSave} disabled={busy} className="mt-3 rounded-lg border border-[var(--line)] px-3 py-2 text-xs font-bold">Save question</button></div>}
